// Turns extraction/data/skills.json into an idempotent SQL upsert.
// Usage (from repo root):
//   node supabase/scripts/seed-skills.mjs > supabase/migrations/<ts>_seed_skills.sql
// Re-run after curating skills.json and commit the new migration.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const skills = JSON.parse(readFileSync(join(here, "../../extraction/data/skills.json"), "utf8"));

const q = (s) => (s == null ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const arr = (a) => (a?.length ? `array[${a.map(q).join(", ")}]::text[]` : "'{}'::text[]");

// sort_order is the array index: the extraction prompt lists skills in file
// order and that order is part of the prompt hash.
const rows = skills.map(
  (s, i) => `  (${q(s.id)}, ${q(s.name)}, ${q(s.domain)}, ${arr(s.aliases)}, ${s.hazard ? "true" : "false"}, ${i})`
);

process.stdout.write(`-- Generated by supabase/scripts/seed-skills.mjs from extraction/data/skills.json.
-- ${skills.length} skills. Do not edit by hand; re-generate.
insert into skills (id, name, domain, aliases, hazard, sort_order) values
${rows.join(",\n")}
on conflict (id) do update set
  name       = excluded.name,
  domain     = excluded.domain,
  aliases    = excluded.aliases,
  hazard     = excluded.hazard,
  sort_order = excluded.sort_order;
`);
