// Produces the deployable web/ directory. Node 20+, no dependencies.
//
//   SUPABASE_URL=… SUPABASE_ANON_KEY=… node web/build.mjs
//   node --env-file=supabase/.env web/build.mjs        (same values locally)
//
// Two things a static host cannot do that web/serve.mjs does:
//
// 1. app.js imports /extraction/src/distance.js so the browser runs the very
//    module the Node report and the tests use (docs/step-5-plan.md, Phase C).
//    The dev server mounts that directory; here it is copied to
//    web/extraction/src/ so the same URL resolves. The copy is a build
//    artifact and gitignored — the committed source stays one file.
// 2. config.js is gitignored (never keys in a tracked file). It is written
//    here from the host's environment variables, so it exists only in the
//    build output. It also carries the deployed commit (Vercel sets
//    VERCEL_GIT_COMMIT_SHA), which the footer shows and a report records.
//
// Output is web/ itself; the host serves this directory.

import { copyFileSync, mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const web = fileURLToPath(new URL("./", import.meta.url));
const src = fileURLToPath(new URL("../extraction/src/distance.js", import.meta.url));

const need = (k) => {
  const v = process.env[k];
  if (!v) { console.error(`${k} is not set`); process.exit(1); }
  return v;
};
const url = need("SUPABASE_URL").replace(/\/$/, "");
const key = need("SUPABASE_ANON_KEY");
const commit = (process.env.VERCEL_GIT_COMMIT_SHA || "").slice(0, 7) || "dev";

mkdirSync(`${web}extraction/src`, { recursive: true });
copyFileSync(src, `${web}extraction/src/distance.js`);

writeFileSync(`${web}config.js`,
  `// generated by web/build.mjs — do not edit, do not commit\n` +
  `export const SUPABASE_URL = ${JSON.stringify(url)};\n` +
  `export const SUPABASE_ANON_KEY = ${JSON.stringify(key)};\n` +
  `export const COMMIT = ${JSON.stringify(commit)};\n`);

console.log(`built web/: extraction/src/distance.js copied, config.js written (commit ${commit})`);
